### ISSUE TITLE
Error preventing start

### ISSUE THREAD

**Issue by iCaitlyn** [Amethyst93/Discord-YouTube-Notifier#7]
```
/root/DiscordYoutubeNotifier/config.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(ymlfile)
Traceback (most recent call last):
  File "./main.py", line 74, in <module>
    client.run(config.getConnectionData()[1])
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/usr/lib/python3.6/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/usr/lib/python3.6/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/usr/lib/python3.6/site-packages/discord/state.py", line 661, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/usr/lib/python3.6/site-packages/discord/state.py", line 636, in _get_create_guild
    guild._from_data(data)
  File "/usr/lib/python3.6/site-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/usr/lib/python3.6/site-packages/discord/guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/usr/lib/python3.6/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/usr/lib/python3.6/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/usr/lib/python3.6/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

**Comment by iCaitlyn** [comment]
Turns out it doesn't like using the same bot as another app

**Comment by iCaitlyn** [comment]
Adding it to a server causes it to fail outright.

With the following error:
```
/root/DiscordYoutubeNotifier/config.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(ymlfile)
Traceback (most recent call last):
  File "./main.py", line 74, in <module>
    client.run(config.getConnectionData()[1])
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/usr/lib/python3.6/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/usr/lib/python3.6/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/usr/lib/python3.6/site-packages/discord/state.py", line 661, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/usr/lib/python3.6/site-packages/discord/state.py", line 636, in _get_create_guild
    guild._from_data(data)
  File "/usr/lib/python3.6/site-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/usr/lib/python3.6/site-packages/discord/guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/usr/lib/python3.6/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/usr/lib/python3.6/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/usr/lib/python3.6/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```
