### ISSUE TITLE
Problem Spotted

### ISSUE THREAD

**Issue by RyanCarlGaming** [Amethyst93/Discord-YouTube-Notifier#8]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from config import Config
  File "/home/runner/YouTube-Notify/config.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

"**HELP ME ON THIS PLS**"

**Comment by HyperCodec** [comment]
i think its a typo, just change yaml to yml in config.py

**Comment by HyperCodec** [comment]
you also have to run `pip install -U yml` on ur pc before running

**Comment by Stift007** [comment]
pip install pyyaml

**Comment by mrgamer45** [comment]
> pip install pyyaml

👍

**Comment by HyperCodec** [comment]
> pip install pyyaml

Lol yeah that's the one (oops)

**Comment by FlM122** [comment]
Traceback (most recent call last):
  File "C:\Users\Мой\Desktop\server\bot.py", line 5, in <module>
    from Implementation import YouTuber
ModuleNotFoundError: No module named 'Implementation'

**Comment by HyperCodec** [comment]
> Traceback (most recent call last): File "C:\Users\Мой\Desktop\server\bot.py", line 5, in from Implementation import YouTuber ModuleNotFoundError: No module named 'Implementation'

why would there be a module called implementation

it would probably be from something.implementation import youtube if that's the case

**Comment by FlM122** [comment]
please help. What code to take for the bot itself to make it work? There are several codes   .py , type: mine.by or config.by where to get the number? Or is it all boring? if so, how to implement it all in one folder or in some other way? help me please (

**Comment by FlM122** [comment]
'charmap' codec can't decode byte 0x98 in position 707: character maps to <undefined>
Press any key to exit the program
